### PR TITLE
If the user provides a port in the "HTTP Threadfin Domain" field, use it

### PR DESCRIPTION
**Pull request by joshjryan**
I use a non-default port for Threadfin.  I wanted to use the "HTTP Threadfin Domain" field in Settings, but if I did that my URLs would all have `:34400` appended to them. This change allows a user to add a value of `192.168.100.50:2525`, and have the software be smart enough to determine if it should use the user-supplied port, or the default.

### CODE REVIEW

**Review by Fyb3roptik — CHANGES_REQUESTED** [review]
This is not allowing me to use only the ip address without a port. 

```
2024/11/04 13:23:09 [Threadfin] [ERROR] listen tcp 192.168.0.53:34400: bind: can't assign requested address (Web server could not be started.) - EC: 1001
2024/11/04 13:23:09 [Threadfin] [ERROR] listen tcp 192.168.0.53:34400: bind: can't assign requested address () - EC: 0
```

Please verify and make sure users can use it without specifying the port

**Comment by joshjryan** [comment]
> This is not allowing me to use only the ip address without a port.

Thanks for checking it out. I felt like I tested it well, but will dig in a little more this afternoon. 
My change _**should**_ have only affected the "HTTP Threadfin Domain" value, not the bind address, so I'll have to figure out why it caused you to get that bind error.  I'll follow up after I test more.

**Comment by joshjryan** [comment]
@Fyb3roptik If I set HTTP Threadfin Domain to `192.168.100.50`, my threadfin.xml looks like this:
image
If I set HTTP Threadfin Domain to `192.168.100.50:2525`, it looks like this:
image
...which is what I expect....I'm not able to reproduce your error...any ideas on how I can reproduce it?

**Comment by joshjryan** [comment]
Just as a data point: I built a docker image from this branch and have been using it for the last handful of days, and haven't run into the issue you saw (even with multiple container restarts).

**Review by Fyb3roptik — APPROVED** [review]

**Pull request merged**
