### PR TITLE
Kill the application VLC/ffmpeg ou similaire and Timeout for streaming

### PR DESCRIPTION
**Pull request by alphalneo**
Force killing the app when the stream is closed and give the possibility to change the timeout in streaming, sometime 20s is not enough

### CODE REVIEW

**Comment by Fyb3roptik** [comment]
I will check this out! If you have fixed this for me I will be so happy. I have been chasing this bug for a bit

**Comment by Fyb3roptik** [comment]
So this is not working for me. It keeps killing the stream.

**Comment by alphalneo** [comment]
> So this is not working for me. It keeps killing the stream.

Are you talking about the timeout?
I forgot this too
if clients.Error != nil || (timeOut > 200 && (playlist.Streams[streamID].BackupChannel1URL == "" && playlist.Streams[streamID].BackupChannel2URL == "" && playlist.Streams[streamID].BackupChannel3URL == "")) {
							killClientConnection(streamID, stream.PlaylistID, false)
							return
						}

this timeout, can you try

**Comment by Fyb3roptik** [comment]
This is being handled already in 1.2.4. I am going to close this PR since it is not working right. It is killing the process no matter what

**Comment by alphalneo** [comment]
Sorry to bother you, for is working 
if clients.Error != nil || (timeOut > (Settings.StreamingTimeout*10) && (playlist.Streams[streamID].BackupChannel1URL == "" && playlist.Streams[streamID].BackupChannel2URL == "" && playlist.Streams[streamID].BackupChannel3URL == ""))
 and for sure you need to modify the StreamingTimeout the default is 20s

Here the image of my output (edited)

Screenshot 2024-08-28 at 12 40 59 PM

**Pull request closed without merging**
